name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm i
      - run: pnpm run fetch

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update alpha token list'
